#!/bin/zsh

# Copy this script to ".git/hooks/pre-push" in this repo to run swiftformat & swiftlint verification before a push.

echo "Running format verification script before push. Testing whether swiftformat and/or swiftlint require changes."

if [[ -n $(git status --porcelain) ]]; then
  echo "Please push to server only with a clean git status"
  exit 1
fi

swiftformat .
if [[ -n $(git status --porcelain) ]]; then
  echo "Swiftformat made some changes. Please verify and commit them before pushing."
  exit 1
fi

swiftlint lint --quiet --strict .
if [ "$?" -ne "0" ]; then
  echo "Linter issues found. Please fix the issues found by swiftlint before pushing to server."
  exit 1
fi

# All is good.
echo "No format or linter issues found. Pushing to server..."
exit 0